import { NavLink, Route, Routes } from 'react-router-dom'
import { useUiStore } from './store'
import { Overview, Payments, Customers } from './MerchantOperations'
import { PaymentDetailOperations } from './PaymentDetailOperations'
import { SmsOperations } from './SmsOperations'
import { ReconciliationOperations, MpesaOperations, SettingsOperations } from './FinalizationOperations'
import { MpesaConnectionsOperations } from './MpesaConnectionsOperations'
import { DeveloperOperations } from './DeveloperOperations'

type Nav={label:string;path:string;icon:string}
const nav:Nav[]=[{label:'Overview',path:'/',icon:'⌂'},{label:'Payments',path:'/payments',icon:'↕'},{label:'Customers',path:'/customers',icon:'○'},{label:'Reconciliation',path:'/reconciliation',icon:'✓'},{label:'M-Pesa',path:'/mpesa',icon:'◈'},{label:'SMS',path:'/sms',icon:'✉'},{label:'Developers',path:'/developers',icon:'{}'},{label:'Settings',path:'/settings',icon:'⚙'}]
function NavItem({item}:{item:Nav}){return <NavLink to={item.path} end={item.path==='/' } className={({isActive})=>`nav-item ${isActive?'active':''}`}><span className="nav-icon">{item.icon}</span>{item.label}</NavLink>}
export default function App(){const {sidebarOpen,toggleSidebar,environment,setEnvironment}=useUiStore();return <div className="app-shell"><aside className={`sidebar ${sidebarOpen?'open':''}`}><div className="brand"><div className="brand-mark">M</div><div><strong>MobiWave</strong><span>Payments</span></div></div><div className="nav-label">Workspace</div><nav>{nav.slice(0,4).map(x=><NavItem key={x.path} item={x}/>)}</nav><div className="nav-label">Operations</div><nav>{nav.slice(4,6).map(x=><NavItem key={x.path} item={x}/>)}</nav><div className="nav-label">Platform</div><nav>{nav.slice(6).map(x=><NavItem key={x.path} item={x}/>)}</nav><div className="connection-card"><div className="connection-row"><span>M-Pesa</span><span className="online"><i/> Managed</span></div><small>Connection and activation are managed from M-Pesa.</small></div></aside>{sidebarOpen&&<button className="scrim" onClick={toggleSidebar} aria-label="Close navigation"/>}<main className="main"><header className="topbar"><button className="menu" onClick={toggleSidebar}>☰</button><div className="crumb">Payments workspace</div><div className="top-actions"><select value={environment} onChange={e=>setEnvironment(e.target.value as 'sandbox'|'production')}><option value="sandbox">Sandbox</option><option value="production">Production</option></select><div className="avatar">MW</div></div></header><div className="content"><Routes><Route path="/" element={<Overview/>}/><Route path="/payments" element={<Payments/>}/><Route path="/payments/:id" element={<PaymentDetailOperations/>}/><Route path="/customers" element={<Customers/>}/><Route path="/reconciliation" element={<ReconciliationOperations/>}/><Route path="/mpesa" element={<MpesaOperations/>}/><Route path="/mpesa/connections" element={<MpesaConnectionsOperations/>}/><Route path="/sms" element={<SmsOperations/>}/><Route path="/developers" element={<DeveloperOperations/>}/><Route path="/settings" element={<SettingsOperations/>}/></Routes></div></main></div>}
