import { useState, type FormEvent } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { api, type Webhook } from './api'

const date=(v?:string|null)=>v?new Intl.DateTimeFormat('en-KE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'
const Loading=()=> <div className="loading-list" aria-busy="true">{[1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>
const Empty=({title,copy}:{title:string;copy:string})=><div className="empty"><strong>{title}</strong><span>{copy}</span></div>
const Alert=({text}:{text:string})=><div className="alert" role="alert">{text}</div>
const tone=(status:string)=>['active','enabled','delivered','success'].includes(status)?'success':['pending','requested','retrying'].includes(status)?'pending':'failed'

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><div className="panel-head"><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Close">×</button></div>{children}</div></div>}

export function DeveloperOperations(){
 const [tab,setTab]=useState<'keys'|'webhooks'|'deliveries'|'playground'>('keys')
 const keys=useQuery({queryKey:['keys'],queryFn:api.apiKeys});const hooks=useQuery({queryKey:['webhooks'],queryFn:api.webhooks});const deliveries=useQuery({queryKey:['webhook-deliveries'],queryFn:()=>api.webhookDeliveries(),enabled:tab==='deliveries'})
 const [secret,setSecret]=useState('');const [name,setName]=useState('Production application');const [url,setUrl]=useState('https://');const [events,setEvents]=useState(['payment.success','payment.failed']);const [edit,setEdit]=useState<Webhook|null>(null);const [showHook,setShowHook]=useState(false)
 const [key,setKey]=useState('');const [payment,setPayment]=useState('');const [result,setResult]=useState('');const [mode,setMode]=useState<'lookup'|'stk'>('lookup');const [phone,setPhone]=useState('');const [amount,setAmount]=useState('')
 const createKey=useMutation({mutationFn:()=>api.createApiKey({name:name.trim(),scopes:['payments:read','payments:write']}),onSuccess:d=>{setSecret(d.secret);keys.refetch()}})
 const revoke=useMutation({mutationFn:api.revokeApiKey,onSuccess:()=>keys.refetch()})
 const saveHook=useMutation({mutationFn:()=>edit?api.updateWebhook(edit.id,{url:url.trim(),events}):api.createWebhook({url:url.trim(),events}),onSuccess:d=>{if('secret' in d&&d.secret)setSecret(d.secret);hooks.refetch();setEdit(null);setShowHook(false)}})
 const disable=useMutation({mutationFn:api.disableWebhook,onSuccess:()=>hooks.refetch()});const retry=useMutation({mutationFn:api.retryWebhookDelivery,onSuccess:()=>deliveries.refetch()})
 const playground=useMutation({mutationFn:()=>mode==='lookup'?api.apiPlayground(`/api/v1/payments/${payment.trim()}`,'GET',key):api.apiPlayground('/api/v1/payments/stk','POST',key,{phone,amount:Number(amount),reference:'TEST',description:'Developer playground test'},`mw_${Date.now()}`),onSuccess:d=>setResult(JSON.stringify(d,null,2)),onError:e=>setResult(e instanceof Error?e.message:'Request failed')})
 const toggle=(event:string)=>setEvents(current=>current.includes(event)?current.filter(v=>v!==event):[...current,event])
 const openCreate=()=>{setEdit(null);setUrl('https://');setEvents(['payment.success','payment.failed']);setShowHook(true)}
 const openEdit=(hook:Webhook)=>{setEdit(hook);setUrl(hook.url);setEvents(hook.events||[]);setShowHook(true)}
 return <>
  <div className="page-head"><div><div className="eyebrow">DEVELOPERS</div><h1>API & webhooks</h1><p>Build integrations with scoped keys, signed events and a live request playground.</p></div></div>
  {secret&&<div className="secret-box"><strong>New secret — copy it now</strong><code>{secret}</code><small>This value is shown once. Store it in your secret manager.</small><button onClick={()=>setSecret('')}>Dismiss</button></div>}
  <div className="dev-tabs" role="tablist" aria-label="Developer tools">{(['keys','webhooks','deliveries','playground'] as const).map(x=><button type="button" key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='keys'?'API keys':x[0].toUpperCase()+x.slice(1)}</button>)}</div>
  {tab==='keys'&&<section className="panel"><div className="panel-head"><div><h2>API keys</h2><span>Use separate keys for each application or service.</span></div><button className="primary" onClick={()=>createKey.mutate()} disabled={createKey.isPending||!name.trim()}>{createKey.isPending?'Creating…':'Create API key'}</button></div><label>Key name<input value={name} onChange={e=>setName(e.target.value)} /></label>{keys.isPending?<Loading/>:keys.data?.keys?.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Key</th><th>Scopes</th><th>Last used</th><th>Status</th><th/></tr></thead><tbody>{keys.data.keys.map(k=><tr key={k.id}><td><strong>{k.name}</strong><small>{date(k.created_at)}</small></td><td><code>{k.key_prefix}••••{k.key_last4}</code></td><td>{k.scopes.join(', ')}</td><td>{date(k.last_used_at)}</td><td><span className={`status ${tone(k.status)}`}>{k.status}</span></td><td><button onClick={()=>revoke.mutate(k.id)} disabled={k.status!=='active'||revoke.isPending}>Revoke</button></td></tr>)}</tbody></table></div>:<Empty title="No API keys" copy="Create a scoped integration key to connect your application."/>}</section>}
  {tab==='webhooks'&&<section className="panel"><div className="panel-head"><div><h2>Webhook endpoints</h2><span>Receive signed payment events at your HTTPS endpoint.</span></div><button className="primary" onClick={openCreate}>Add endpoint</button></div>{hooks.isPending?<Loading/>:hooks.data?.endpoints?.length?<div className="table-wrap"><table><thead><tr><th>Endpoint</th><th>Events</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{hooks.data.endpoints.map(h=><tr key={h.id}><td><strong>{h.url}</strong></td><td>{h.events?.join(', ')||'—'}</td><td><span className={`status ${tone(h.status)}`}>{h.status}</span></td><td>{date(h.updated_at||h.created_at)}</td><td><div className="table-actions"><button onClick={()=>openEdit(h)}>Edit</button><button onClick={()=>disable.mutate(h.id)} disabled={disable.isPending}>Disable</button></div></td></tr>)}</tbody></table></div>:<Empty title="No webhook endpoints" copy="Add an HTTPS endpoint to receive payment events."/>}</section>}
  {tab==='deliveries'&&<section className="panel"><div className="panel-head"><div><h2>Webhook deliveries</h2><span>Inspect delivery attempts and retry failures.</span></div></div>{deliveries.isPending?<Loading/>:deliveries.data?.deliveries?.length?<div className="table-wrap"><table><thead><tr><th>Event</th><th>Status</th><th>Attempts</th><th>HTTP</th><th>Created</th><th/></tr></thead><tbody>{deliveries.data.deliveries.map(d=><tr key={d.id}><td><strong>{d.event_type}</strong><small>{d.event_id}</small></td><td><span className={`status ${tone(d.status)}`}>{d.status}</span></td><td>{d.attempt_count}</td><td>{d.response_status||'—'}</td><td>{date(d.created_at)}</td><td>{d.status!=='delivered'&&<button onClick={()=>retry.mutate(d.id)} disabled={retry.isPending}>{retry.isPending?'Retrying…':'Retry'}</button>}</td></tr>)}</tbody></table></div>:<Empty title="No deliveries" copy="Webhook delivery history will appear here."/>}</section>}
  {tab==='playground'&&<section className="two-col"><div className="panel"><div className="panel-head"><div><h2>API request</h2><span>Test the merchant API without leaving the portal.</span></div></div><label>API key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste a secret key" /></label><label>Operation<select value={mode} onChange={e=>setMode(e.target.value as 'lookup'|'stk')}><option value="lookup">GET payment by ID</option><option value="stk">POST STK Push</option></select></label>{mode==='lookup'?<label>Payment ID<input value={payment} onChange={e=>setPayment(e.target.value)} placeholder="Payment ID"/></label>:<><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="07XXXXXXXX"/></label><label>Amount (KES)<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label></>}<div className="form-actions"><button className="primary" onClick={()=>playground.mutate()} disabled={!key||playground.isPending|| (mode==='lookup'&&!payment.trim()) || (mode==='stk'&&(!phone||Number(amount)<1))}>{playground.isPending?'Sending…':'Send request'}</button></div></div><div className="panel"><div className="panel-head"><div><h2>Response</h2><span>{result?'Latest API response':'Waiting for a request'}</span></div></div><pre className="code-output">{result||'Run a request to inspect the API response.'}</pre></div></section>}
  {createKey.error&&<Alert text={createKey.error instanceof Error?createKey.error.message:'Unable to create API key.'}/>} {saveHook.error&&<Alert text={saveHook.error instanceof Error?saveHook.error.message:'Unable to save webhook.'}/>} {revoke.error&&<Alert text="Unable to revoke API key."/>}
  {showHook&&<Modal title={edit?'Edit webhook endpoint':'Add webhook endpoint'} onClose={()=>setShowHook(false)}><form className="form-grid" onSubmit={(e:FormEvent)=>{e.preventDefault();if(url.trim()&&events.length)saveHook.mutate()}}><label>Endpoint URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://api.example.com/webhooks" required /></label><fieldset><legend>Events</legend><label className="check-row"><input type="checkbox" checked={events.includes('payment.success')} onChange={()=>toggle('payment.success')}/> Payment succeeded</label><label className="check-row"><input type="checkbox" checked={events.includes('payment.failed')} onChange={()=>toggle('payment.failed')}/> Payment failed</label></fieldset><div className="form-actions"><button type="button" onClick={()=>setShowHook(false)}>Cancel</button><button className="primary" type="submit" disabled={saveHook.isPending||!url.trim()||!events.length}>{saveHook.isPending?'Saving…':edit?'Save changes':'Add endpoint'}</button></div></form></Modal>}
 </>
}
