import { FormEvent, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useMutation, useQuery } from '@tanstack/react-query'
import { api, type Payment, type PaymentStatus } from './api'
import { PaymentDetailOperations } from './PaymentDetailOperations'

export const money=(v:number|string)=>`KES ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`
export const date=(v?:string|null)=>v?new Intl.DateTimeFormat('en-KE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'
export const maskPhone=(v?:string|null)=>v?`${v.slice(0,6)}••••${v.slice(-2)}`:'Customer'
export function usePayments(){const stats=useQuery({queryKey:['dashboard','stats'],queryFn:api.stats});const payments=useQuery({queryKey:['payments'],queryFn:()=>api.payments()});return {stats:stats.data,rows:payments.data?.transactions??payments.data?.data??[],loading:stats.isPending||payments.isPending,error:stats.error||payments.error}}
const Alert=({text}:{text:string})=><div className="alert">{text}</div>
const Loading=()=> <div className="loading-list">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>
const Metric=({label,value,meta,warning}:{label:string;value:string;meta:string;warning?:boolean})=><div className="metric"><span>{label}</span><strong className={warning?'warning':''}>{value}</strong><small>{meta}</small></div>
const Head=({title,action,href}:{title:string;action?:string;href?:string})=><div className="panel-head"><h2>{title}</h2>{action&&(href?<Link to={href}>{action} →</Link>:<span>{action}</span>)}</div>
const Status=({status}:{status:PaymentStatus})=><span className={`status ${status}`}>{status==='success'?'Successful':status==='pending'?'Pending':status==='failed'?'Failed':'Reversed'}</span>
const Empty=({title,copy}:{title:string;copy:string})=><div className="empty"><strong>{title}</strong><span>{copy}</span></div>
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=><div className="modal-backdrop"><div className="modal"><div className="panel-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>
function Table({rows,onOpen}:{rows:Payment[];onOpen?:(id:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>Customer</th><th>Amount</th><th>Reference</th><th>Status</th><th>Receipt</th><th>Time</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id} className={onOpen?'clickable':''} onClick={()=>onOpen?.(r.id)}><td><strong>{maskPhone(r.phone_number)}</strong><small>{r.transaction_type||'M-Pesa'}</small></td><td>{money(r.amount)}</td><td>{r.reference||'—'}</td><td><Status status={r.status}/></td><td>{r.mpesa_receipt||'—'}</td><td>{date(r.created_at)}</td></tr>):<tr><td colSpan={6}><Empty title="No payments found" copy="Try another search or wait for your first payment."/></td></tr>}</tbody></table></div>}
export function Overview(){const {stats,rows,loading,error}=usePayments();const rate=stats?.totalTransactions?((stats.successfulPayments/stats.totalTransactions)*100).toFixed(1):'0.0';return <><div className="page-head"><div><div className="eyebrow">OVERVIEW</div><h1>Good afternoon</h1><p>Your payment system is healthy today.</p></div><Link className="primary" to="/payments">Request payment</Link></div>{error&&<Alert text="Live payment data could not be loaded."/>}<section className="metric-grid"><Metric label="Collected" value={money(stats?.totalAmount||0)} meta="Recorded payments"/><Metric label="Payments" value={String(stats?.totalTransactions||0)} meta="Transactions"/><Metric label="Success rate" value={`${rate}%`} meta="Successful payments"/><Metric label="Needs attention" value={String(stats?.failedPayments||0)} meta="Failed payments" warning/></section><section className="two-col"><div className="panel"><Head title="Payment activity" action="Last 7 days"/><div className="bars">{[0,1,2,3,4,5,6].map((_,i)=><div className="bar-col" key={i}><div className="bar" style={{height:`${Math.max(8,((i+1)%4+1)*18)}%`}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></div><div className="panel health"><Head title="System health"/><HealthRow label="M-Pesa connection" value="Connected"/><HealthRow label="Payment callbacks" value="Healthy"/><HealthRow label="SMS receipts" value="Ready"/><HealthRow label="Webhook queue" value="Healthy"/></div></section><section className="panel"><Head title="Recent payments" action="View all" href="/payments"/>{loading?<Loading/>:<Table rows={rows.slice(0,7)}/>}</section></>}
function HealthRow({label,value}:{label:string;value:string}){return <div className="health-row"><span>{label}</span><span className="health-value"><i/>{value}</span></div>}
export function Payments(){const nav=useNavigate();const {rows,loading,error}=usePayments();const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [open,setOpen]=useState(false);const filtered=useMemo(()=>rows.filter(r=>(!search||[r.phone_number,r.reference,r.mpesa_receipt,r.transaction_id].join(' ').toLowerCase().includes(search.toLowerCase()))&&(!status||r.status===status)),[rows,search,status]);return <><div className="page-head"><div><div className="eyebrow">OPERATIONS</div><h1>Payments</h1><p>Track collections and send M-Pesa payment requests.</p></div><button className="primary" onClick={()=>setOpen(true)}>Request payment</button></div>{error&&<Alert text="Live payments could not be loaded."/>}<div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search phone, receipt or reference"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="success">Successful</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="reversed">Reversed</option></select><button onClick={()=>{setSearch('');setStatus('')}}>Clear</button></div><section className="panel">{loading?<Loading/>:<Table rows={filtered} onOpen={id=>nav(`/payments/${id}`)}/>}</section>{open&&<StkModal onClose={()=>setOpen(false)}/>}</>}
function StkModal({onClose}:{onClose:()=>void}){const [phone,setPhone]=useState('');const [amount,setAmount]=useState('');const [reference,setReference]=useState('PAYMENT');const mutation=useMutation({mutationFn:api.stk});return <Modal title="Request M-Pesa payment" onClose={onClose}><form onSubmit={e=>{e.preventDefault();mutation.mutate({phone,amount:Number(amount),reference:reference.slice(0,12),description:'MobiWave payment'})}} className="form-grid"><label>Customer phone<input value={phone} onChange={e=>setPhone(e.target.value)} required placeholder="07xx xxx xxx"/></label><label>Amount (KES)<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Reference<input maxLength={12} value={reference} onChange={e=>setReference(e.target.value)} required/></label><div className="form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={mutation.isPending}>{mutation.isPending?'Sending…':'Send STK Push'}</button></div>{mutation.error&&<Alert text={mutation.error instanceof Error?mutation.error.message:'Unable to send payment request.'}/>} {mutation.data&&<Alert text="STK Push sent. The customer can now complete the M-Pesa prompt."/>}</form></Modal>}
export function Customers(){const {rows,loading}=usePayments();const [search,setSearch]=useState('');const customers=useMemo(()=>{const map=new Map<string,{phone:string;count:number;amount:number;last:string}>();rows.forEach(p=>{const phone=p.phone_number||'Unknown';const c=map.get(phone)||{phone,count:0,amount:0,last:p.created_at};c.count++;c.amount+=Number(p.amount||0);if(new Date(p.created_at)>new Date(c.last))c.last=p.created_at;map.set(phone,c)});return [...map.values()].filter(x=>x.phone.toLowerCase().includes(search.toLowerCase()))},[rows,search]);return <><div className="page-head"><div><div className="eyebrow">CUSTOMERS</div><h1>Customers</h1><p>Customers are built automatically from payment activity.</p></div></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer phone"/></div><section className="panel">{loading?<Loading/>:<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Payments</th><th>Total collected</th><th>Last payment</th></tr></thead><tbody>{customers.map(c=><tr key={c.phone}><td><strong>{maskPhone(c.phone)}</strong></td><td>{c.count}</td><td>{money(c.amount)}</td><td>{date(c.last)}</td></tr>)}{!customers.length&&<tr><td colSpan={4}><Empty title="No customers yet" copy="Customers appear after payments are recorded."/></td></tr>}</tbody></table></div>}</section></>}
export { PaymentDetailOperations }
